# Generated by Django 2.2.4 on 2019-10-09 16:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('fatherlastname', models.CharField(max_length=40, verbose_name='Apellido Paterno')),
                ('motherlastname', models.CharField(max_length=40, verbose_name='Apellido Materno')),
                ('sex', models.CharField(max_length=10, verbose_name='Genero HM-LGBTTTIQ')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Cumpleaños')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('celphone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número celular')),
                ('workplace', models.CharField(max_length=40, verbose_name='Lugar de trabajo')),
                ('workphone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Número de telefono del trabajo')),
                ('facebook', models.CharField(blank=True, max_length=40, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=40, null=True, verbose_name='Instagram')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Datos adicionales')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='clients_files', verbose_name='Foto')),
                ('sign', models.ImageField(blank=True, null=True, upload_to='clients_files', verbose_name='Firma responsiva')),
                ('assessment', models.ImageField(blank=True, null=True, upload_to='clients_files', verbose_name='Valoración')),
                ('packsheet', models.ImageField(blank=True, null=True, upload_to='clients_files', verbose_name='Hoja de paquete')),
                ('consent', models.ImageField(blank=True, null=True, upload_to='clients_files', verbose_name='Consentimiento informado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created'],
            },
        ),
    ]
