# Generated by Django 2.2.3 on 2019-07-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('fatherlastname', models.CharField(max_length=40, verbose_name='Apellido Paterno')),
                ('motherlastname', models.CharField(max_length=40, verbose_name='Apellido Materno')),
                ('sex', models.CharField(max_length=10, verbose_name='Genero HM-LGBTTTIQ')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='Cumpleaños')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono')),
                ('work', models.CharField(blank=True, max_length=40, null=True, verbose_name='Trabajo')),
                ('facebook', models.CharField(blank=True, max_length=40, null=True, verbose_name='Facebook')),
                ('description', models.TextField(verbose_name='Datos adicionales')),
                ('image', models.ImageField(upload_to='promotion_files', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-created'],
            },
        ),
    ]
