# Generated by Django 2.2.3 on 2019-07-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20190713_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Datos adicionales'),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='promotion_files', verbose_name='Imagen'),
        ),
    ]
