# Generated by Django 2.2.4 on 2019-09-13 18:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20190713_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Datos adicionales'),
        ),
    ]
