# Generated by Django 2.2.1 on 2019-08-27 18:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casefile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=ckeditor.fields.RichTextField(max_length=100, verbose_name='Nombre'),
        ),
    ]
