# Generated by Django 2.2.1 on 2019-08-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['name'], 'verbose_name': 'Enlace social', 'verbose_name_plural': 'Enlaces sociales'},
        ),
    ]
