# Generated by Django 2.2.4 on 2019-10-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created'], 'verbose_name': 'paquete', 'verbose_name_plural': 'paquetes'},
        ),
    ]
