# Generated by Django 2.2.3 on 2019-07-13 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
    ]
