"""
Django settings for zproyect project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fyncqn6xrpsocc%s$!su5--&x2&e2y5i!v=cl+p^6(_1-tws1+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['lovelyspa.tk','lovelyspa.pythonanywhere.com','localhost','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'registration',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
    #Originalmente se manda llamar el archivo promociones
    #'promotion',
    #Pero con el nuevo comando se le pide que llame la configuracion extendida
    #Para que con eso acepte el nuevo nombre
    'promotion.apps.PromotionConfig',
    'blog',
    'services.apps.ServicesConfig',
    'social.apps.SocialConfig',
    'pages.apps.PagesConfig',
    'ckeditor',
    'contact',
    'clients.apps.ClientsConfig',
    'casefile.apps.CasefileConfig',
    'employee',
    'cuba',
    'box',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zproyect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social.processors.ctx_dict',
            ],
        },
    },
]

WSGI_APPLICATION = 'zproyect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

#Configuración en modo prueba
DATABASES = {
    'default': {
        'NAME': 'al.spa',
        'ENGINE': 'mysql.connector.django',
        'USER': 'alspa',
        'PASSWORD': '$ba51P15cu5',
        'OPTIONS': {
          'autocommit': True,
      },
    }
}

#Configuración en py any where
#
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'dlunna$alspa',
#        'USER': 'dlunna',
#        'PASSWORD': '$ba51P15cu5',
#        'HOST': 'lovelyspa.mysql.pythonanywhere-services.com',
#    }
#}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# Se agrega esta configuración extendia para que django
# coloque los archivos multimedia dentro de la carpeta media
# tambien modicar el modelo en el campo image
MEDIA_URL = '/media/'
# en donde tiene que ir a buscar el directorio media
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Ckeditor
# Configuracion personalizada para el ckeditor
# pip install django-ckeditor
# Añarir en el modelo
# habilitar en installed app en settings
# en la vista en vez de linebraks poner safe
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ],
        'width': 'auto',
    }
}

# Email config
EMAIL_HOST = 'smtp.mailtrap.io'
EMAIL_HOST_USER = 'bfa56e53a99138'
EMAIL_HOST_PASSWORD = 'b5f733131373d1'
EMAIL_PORT = '2525'


# Auth redirects 'redireccion para la app registration'
LOGIN_REDIRECT_URL = 'empleados'
LOGOUT_REDIRECT_URL = 'root'