# Generated by Django 2.2.4 on 2019-10-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='key',
        ),
    ]
