# Generated by Django 2.2.1 on 2019-07-02 23:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190701_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 23, 19, 38, 211820, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
