# Generated by Django 2.2.1 on 2019-07-02 23:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190702_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 2, 23, 23, 49, 697287, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
