# Generated by Django 2.2.1 on 2019-07-05 21:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190705_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 21, 34, 37, 449456, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
