# Generated by Django 2.2.1 on 2019-07-05 22:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190705_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 5, 22, 0, 14, 992847, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
