# Generated by Django 2.2.3 on 2019-07-13 22:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190705_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 22, 29, 50, 235076, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
