# Generated by Django 2.2.3 on 2019-07-13 23:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190713_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 23, 2, 6, 644245, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
