# Generated by Django 2.2.3 on 2019-07-13 23:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190713_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 23, 17, 51, 608915, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
