# Generated by Django 2.2.1 on 2019-08-22 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20190713_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 18, 35, 51, 223285, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
