# Generated by Django 2.2.1 on 2019-08-22 23:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190822_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 23, 5, 19, 871261, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
