# Generated by Django 2.2.1 on 2019-08-22 23:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20190822_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 23, 6, 57, 972913, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
